const stations = Array.from(document.querySelectorAll(".station"));

const stationLabels = [
  "Learn",
  "Tokens",
  "Context",
  "Network",
  "Prediction",
  "Generation",
  "Hallucination",
  "Whole Model"
];

const trainingPhases = [
  {
    label: "Read",
    title: "Pretraining",
    kicker: "Read enormous amounts of material",
    analogy: "The student reads a huge library and gradually discovers patterns in language.",
    equivalent: "Large amounts of text -> Predict missing or next tokens -> Learn language patterns"
  },
  {
    label: "Examples",
    title: "Supervised Fine Tuning",
    kicker: "Study examples of good answers",
    analogy: "The teacher shows questions paired with ideal answers, so the student learns what a useful response should look like.",
    equivalent: "Prompt -> Desired response -> Better instruction following"
  },
  {
    label: "Feedback",
    title: "Reinforcement Learning",
    kicker: "Practise, receive feedback, improve strategies",
    analogy: "The student attempts answers, receives feedback or rewards, adjusts strategies, and tries again.",
    equivalent: "Attempt -> Feedback or reward -> Adjustment -> Try again"
  }
];

const terms = [
  ["Token", "A small unit of text that a language model processes."],
  ["Context", "The text currently available to the model while it generates the next token."],
  ["Neural Network", "A large collection of connected computational units that transforms token patterns into predictions."],
  ["Parameters", "Values learned during training that encode patterns discovered from data."],
  ["Training Data", "Examples used to teach the model statistical patterns in language."],
  ["Pretraining", "The broad training stage where a model learns from large text collections by predicting missing or next text."],
  ["Supervised Fine Tuning", "Further training using examples of desired inputs and responses."],
  ["Reinforcement Learning", "A learning approach in which a model improves behaviour using feedback or rewards associated with its outputs."],
  ["Next Token Probability", "The model's estimate of how likely each possible next token is."],
  ["Inference", "Using a trained model to produce an output."],
  ["Hallucination", "A plausible sounding but incorrect or unsupported response generated by an AI model."]
];

const tokenExamples = {
  default: "Artificial intelligence is changing education.",
  context: "The capital of India is",
  learning: "AI can help students"
};

const contextPresets = [
  {
    id: "capital",
    label: "Capital",
    text: "The capital of India is",
    note: "The next token is strongly guided toward a place name.",
    probabilitySets: {
      0: [
        ["Delhi", 92],
        ["Mumbai", 3],
        ["Jaipur", 2],
        ["Kolkata", 1],
        ["Other", 2]
      ],
      1: [
        ["Delhi", 68],
        ["Mumbai", 12],
        ["Jaipur", 7],
        ["Kolkata", 5],
        ["Other", 8]
      ],
      2: [
        ["Delhi", 46],
        ["Mumbai", 22],
        ["Jaipur", 13],
        ["Kolkata", 9],
        ["Other", 10]
      ]
    },
    generationTokens: ["Delhi", "and", "it", "serves", "as", "India's", "national", "capital."]
  },
  {
    id: "classroom",
    label: "Classroom",
    text: "AI can help students by",
    note: "The next token is guided toward an educational action.",
    probabilitySets: {
      0: [
        ["explaining", 44],
        ["practising", 24],
        ["summarising", 16],
        ["answering", 10],
        ["other", 6]
      ],
      1: [
        ["explaining", 31],
        ["practising", 24],
        ["creating", 19],
        ["summarising", 15],
        ["other", 11]
      ],
      2: [
        ["explaining", 24],
        ["creating", 23],
        ["practising", 21],
        ["questioning", 17],
        ["other", 15]
      ]
    },
    generationTokens: ["explaining", "concepts", "step", "by", "step", "with", "examples."]
  },
  {
    id: "unclear",
    label: "Unclear",
    text: "It is",
    note: "A vague context leaves many possible continuations.",
    probabilitySets: {
      0: [
        ["important", 24],
        ["possible", 22],
        ["clear", 19],
        ["not", 18],
        ["other", 17]
      ],
      1: [
        ["possible", 22],
        ["important", 21],
        ["unclear", 19],
        ["not", 18],
        ["other", 20]
      ],
      2: [
        ["raining", 20],
        ["possible", 19],
        ["unclear", 19],
        ["late", 18],
        ["other", 24]
      ]
    },
    generationTokens: ["important", "but", "the", "meaning", "depends", "on", "context."]
  }
];
const hallucinationTokens = [
  ["invented", 34],
  ["by", 31],
  ["Eleanor", 18],
  ["Marsh", 12],
  ["in", 5]
];

let currentStation = 0;
let highestUnlocked = 0;
let autoTimer = null;
let generationIndex = 0;
let generationTimer = null;
let selectedContext = contextPresets[0];
let selectedNextToken = null;

const elements = {
  header: document.querySelector(".app-header"),
  progressBar: document.querySelector("#progressBar"),
  stationRail: document.querySelector("#stationRail"),
  prevButton: document.querySelector("#prevButton"),
  nextButton: document.querySelector("#nextButton"),
  autoButton: document.querySelector("#autoButton"),
  restartTop: document.querySelector("#restartTop"),
  termsToggle: document.querySelector("#termsToggle"),
  termsClose: document.querySelector("#termsClose"),
  termsPanel: document.querySelector("#termsPanel"),
  termsList: document.querySelector("#termsList"),
  trainingPhaseList: document.querySelector("#trainingPhaseList"),
  trainingKicker: document.querySelector("#trainingKicker"),
  trainingTitle: document.querySelector("#trainingTitle"),
  trainingAnalogy: document.querySelector("#trainingAnalogy"),
  trainingEquivalent: document.querySelector("#trainingEquivalent"),
  tokenInput: document.querySelector("#tokenInput"),
  rawText: document.querySelector("#rawText"),
  tokenOutput: document.querySelector("#tokenOutput"),
  tokenizeButton: document.querySelector("#tokenizeButton"),
  restoreSentenceButton: document.querySelector("#restoreSentenceButton"),
  tokenNote: document.querySelector("#tokenNote"),
  contextPresets: document.querySelector("#contextPresets"),
  contextTray: document.querySelector("#contextTray"),
  contextCount: document.querySelector("#contextCount"),
  capacitySlider: document.querySelector("#capacitySlider"),
  capacityValue: document.querySelector("#capacityValue"),
  networkTokens: document.querySelector("#networkTokens"),
  networkSignal: document.querySelector("#networkSignal"),
  networkPanel: document.querySelector(".network-panel"),
  processButton: document.querySelector("#processButton"),
  predictionContext: document.querySelector("#predictionContext"),
  probabilityList: document.querySelector("#probabilityList"),
  temperatureSlider: document.querySelector("#temperatureSlider"),
  temperatureValue: document.querySelector("#temperatureValue"),
  sampleButton: document.querySelector("#sampleButton"),
  resetPredictionButton: document.querySelector("#resetPredictionButton"),
  selectedToken: document.querySelector("#selectedToken"),
  generationContext: document.querySelector("#generationContext"),
  generatedText: document.querySelector("#generatedText"),
  stepGenerateButton: document.querySelector("#stepGenerateButton"),
  autoGenerateButton: document.querySelector("#autoGenerateButton"),
  resetGenerationButton: document.querySelector("#resetGenerationButton"),
  hallucinationDemo: document.querySelector("#hallucinationDemo"),
  hallucinationProbabilities: document.querySelector("#hallucinationProbabilities")
};

document.addEventListener("DOMContentLoaded", () => {
  renderStationRail();
  renderTerms();
  renderTrainingPhases();
  bindEvents();
  renderTrainingPhase(0);
  tokenizeCurrentSentence(false);
  renderContextPresets();
  renderContextTray();
  renderNetworkTokens();
  renderProbabilities();
  renderGeneration();
  renderHallucinationProbabilities();
  updateStation(0);
});

function bindEvents() {
  window.addEventListener("scroll", () => {
    elements.header.dataset.elevated = String(window.scrollY > 6);
  });

  elements.prevButton.addEventListener("click", () => updateStation(currentStation - 1));
  elements.nextButton.addEventListener("click", () => updateStation(currentStation + 1));
  elements.restartTop.addEventListener("click", restartLab);
  elements.autoButton.addEventListener("click", toggleAutoWalkthrough);
  elements.termsToggle.addEventListener("click", toggleTerms);
  elements.termsClose.addEventListener("click", closeTerms);

  elements.tokenInput.addEventListener("input", () => {
    elements.rawText.textContent = elements.tokenInput.value || " ";
    elements.tokenNote.textContent = "Sentence edited. Tokenize again to see the new sequence.";
  });
  elements.tokenizeButton.addEventListener("click", () => tokenizeCurrentSentence(true));
  elements.restoreSentenceButton.addEventListener("click", () => {
    elements.tokenInput.value = tokenExamples.default;
    elements.rawText.textContent = tokenExamples.default;
    tokenizeCurrentSentence(true);
  });

  elements.capacitySlider.addEventListener("input", () => {
    renderContextTray();
    renderNetworkTokens();
  });

  elements.processButton.addEventListener("click", processNetwork);
  elements.temperatureSlider.addEventListener("input", renderProbabilities);
  elements.sampleButton.addEventListener("click", sampleNextToken);
  elements.resetPredictionButton.addEventListener("click", resetPrediction);
  elements.stepGenerateButton.addEventListener("click", stepGeneration);
  elements.autoGenerateButton.addEventListener("click", toggleGenerationAuto);
  elements.resetGenerationButton.addEventListener("click", resetGeneration);

  document.querySelectorAll("[data-truth]").forEach(button => {
    button.addEventListener("click", revealHallucination);
  });

  document.addEventListener("keydown", event => {
    if (event.key === "ArrowRight") updateStation(currentStation + 1);
    if (event.key === "ArrowLeft") updateStation(currentStation - 1);
    if (event.key === "Escape") closeTerms();
  });
}

function renderStationRail() {
  elements.stationRail.innerHTML = stationLabels
    .map((label, index) => `
      <button class="station-tab" type="button" data-jump="${index}">
        ${index + 1}. ${label}
      </button>
    `)
    .join("");

  elements.stationRail.querySelectorAll("[data-jump]").forEach(button => {
    button.addEventListener("click", () => updateStation(Number(button.dataset.jump)));
  });
}

function renderTerms() {
  elements.termsList.innerHTML = terms
    .map(([term, description]) => `
      <article class="term-item">
        <strong>${term}</strong>
        <p>${description}</p>
      </article>
    `)
    .join("");
}

function renderTrainingPhases() {
  elements.trainingPhaseList.innerHTML = trainingPhases
    .map((phase, index) => `
      <button class="training-phase" type="button" data-training-phase="${index}">
        <span>${phase.label}</span>
        <strong>${phase.title}</strong>
      </button>
    `)
    .join("");

  elements.trainingPhaseList.querySelectorAll("[data-training-phase]").forEach(button => {
    button.addEventListener("click", () => renderTrainingPhase(Number(button.dataset.trainingPhase)));
  });
}

function renderTrainingPhase(index) {
  const phase = trainingPhases[index];
  elements.trainingKicker.textContent = phase.kicker;
  elements.trainingTitle.textContent = phase.title;
  elements.trainingAnalogy.textContent = phase.analogy;
  elements.trainingEquivalent.textContent = phase.equivalent;

  elements.trainingPhaseList.querySelectorAll("[data-training-phase]").forEach((button, buttonIndex) => {
    button.classList.toggle("is-selected", buttonIndex === index);
  });
}

function updateStation(nextStation) {
  const boundedStation = Math.max(0, Math.min(stations.length - 1, nextStation));
  currentStation = boundedStation;
  highestUnlocked = Math.max(highestUnlocked, currentStation);

  stations.forEach((station, index) => {
    station.classList.toggle("is-active", index === currentStation);
    station.setAttribute("aria-hidden", String(index !== currentStation));
  });

  elements.stationRail.querySelectorAll(".station-tab").forEach((tab, index) => {
    tab.classList.toggle("is-active", index === currentStation);
    tab.classList.toggle("is-complete", index < highestUnlocked);
    tab.disabled = index > highestUnlocked + 1;
  });

  elements.prevButton.disabled = currentStation === 0;
  elements.nextButton.disabled = currentStation === stations.length - 1;
  elements.progressBar.style.width = `${(currentStation / (stations.length - 1)) * 100}%`;
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function restartLab() {
  stopAutoWalkthrough();
  stopGenerationAuto();
  highestUnlocked = 0;
  elements.tokenInput.value = tokenExamples.default;
  elements.rawText.textContent = tokenExamples.default;
  elements.hallucinationDemo.hidden = true;
  resetPrediction();
  resetGeneration();
  tokenizeCurrentSentence(false);
  updateStation(0);
}

function toggleAutoWalkthrough() {
  if (autoTimer) {
    stopAutoWalkthrough();
    return;
  }

  elements.autoButton.setAttribute("aria-pressed", "true");
  elements.autoButton.querySelector("span:last-child").textContent = "Pause";
  autoTimer = window.setInterval(() => {
    if (currentStation >= stations.length - 1) {
      stopAutoWalkthrough();
      return;
    }
    updateStation(currentStation + 1);
  }, 5200);
}

function stopAutoWalkthrough() {
  if (autoTimer) {
    window.clearInterval(autoTimer);
    autoTimer = null;
  }
  elements.autoButton.setAttribute("aria-pressed", "false");
  elements.autoButton.querySelector("span:last-child").textContent = "Auto Walkthrough";
}

function toggleTerms() {
  const isOpen = elements.termsToggle.getAttribute("aria-expanded") === "true";
  if (isOpen) {
    closeTerms();
  } else {
    elements.termsPanel.hidden = false;
    elements.termsToggle.setAttribute("aria-expanded", "true");
  }
}

function closeTerms() {
  elements.termsPanel.hidden = true;
  elements.termsToggle.setAttribute("aria-expanded", "false");
}

function tokenizeCurrentSentence(animate) {
  const text = elements.tokenInput.value.trim() || tokenExamples.default;
  const tokens = tokenize(text);
  elements.rawText.textContent = text;
  elements.tokenOutput.innerHTML = tokens
    .map((token, index) => `<span class="token-pill" style="animation-delay:${animate ? index * 45 : 0}ms">${escapeHtml(token)}</span>`)
    .join("");
  elements.tokenNote.textContent = `${tokens.length} tokens are now visible. The model receives this ordered sequence.`;
}

function tokenize(text) {
  const roughPieces = text.match(/[A-Za-z]+|[0-9]+|[^\sA-Za-z0-9]/g) || [];
  return roughPieces.flatMap(piece => {
    if (/^[A-Za-z]{11,}$/.test(piece)) {
      const midpoint = Math.ceil(piece.length / 2);
      return [piece.slice(0, midpoint), piece.slice(midpoint)];
    }
    return [piece];
  });
}

function renderContextPresets() {
  elements.contextPresets.innerHTML = contextPresets
    .map((preset, index) => `<button type="button" data-context="${index}">${preset.label}</button>`)
    .join("");

  elements.contextPresets.querySelectorAll("[data-context]").forEach(button => {
    button.addEventListener("click", () => {
      selectedContext = contextPresets[Number(button.dataset.context)];
      renderContextTray();
      renderNetworkTokens();
      resetPrediction();
      resetGeneration();
    });
  });
}

function renderContextTray() {
  const capacity = Number(elements.capacitySlider.value);
  const tokens = tokenize(selectedContext.text);
  const visible = tokens.slice(-capacity);
  const hiddenCount = Math.max(0, tokens.length - visible.length);

  elements.capacityValue.textContent = String(capacity);
  elements.contextCount.textContent = `${tokens.length} token${tokens.length === 1 ? "" : "s"}`;
  elements.contextTray.innerHTML = [
    ...Array.from({ length: hiddenCount }, (_, index) => `<span class="token-pill is-muted">older ${index + 1}</span>`),
    ...visible.map(token => `<span class="token-pill">${escapeHtml(token)}</span>`)
  ].join("");

  elements.contextPresets.querySelectorAll("[data-context]").forEach((button, index) => {
    button.classList.toggle("is-selected", contextPresets[index] === selectedContext);
  });

  const insight = document.querySelector(".insight-box span");
  insight.textContent = selectedContext.note;
}

function renderNetworkTokens() {
  const visibleTokens = tokenize(selectedContext.text).slice(-4);
  elements.networkTokens.innerHTML = visibleTokens
    .map(token => `<span class="token-pill">${escapeHtml(token)}</span>`)
    .join("");
}

function processNetwork() {
  elements.networkPanel.classList.add("is-processing");
  elements.networkSignal.textContent = "Processing";
  elements.processButton.disabled = true;

  window.setTimeout(() => {
    elements.networkPanel.classList.remove("is-processing");
    elements.networkSignal.textContent = "Next token scores ready";
    elements.processButton.disabled = false;
  }, 1350);
}

function renderProbabilities() {
  const temperature = Number(elements.temperatureSlider.value);
  const labels = ["Low", "Medium", "Higher"];
  const probabilities = selectedContext.probabilitySets[temperature];
  elements.predictionContext.textContent = selectedContext.text;
  elements.temperatureValue.textContent = labels[temperature];
  elements.probabilityList.innerHTML = probabilities
    .map(([token, value]) => probabilityRow(token, value))
    .join("");
  elements.selectedToken.hidden = true;
  selectedNextToken = null;
}

function sampleNextToken() {
  const temperature = Number(elements.temperatureSlider.value);
  const selected = selectedContext.probabilitySets[temperature][0][0];
  selectedNextToken = selected;
  elements.selectedToken.hidden = false;
  elements.selectedToken.querySelector("strong").textContent = selected;

  elements.probabilityList.querySelectorAll(".probability-row").forEach(row => {
    row.classList.toggle("is-selected", row.dataset.token === selected);
  });
}

function resetPrediction() {
  elements.temperatureSlider.value = "0";
  renderProbabilities();
}

function stepGeneration() {
  if (generationIndex >= selectedContext.generationTokens.length) {
    return;
  }
  generationIndex += 1;
  renderGeneration();
}

function renderGeneration() {
  const nextToken = selectedNextToken || selectedContext.probabilitySets[0][0][0];
  const continuationTokens = selectedContext.generationTokens[0] === nextToken
    ? selectedContext.generationTokens.slice(1)
    : selectedContext.generationTokens;
  const visibleTokens = [
    ...tokenize(selectedContext.text),
    ...(generationIndex > 0 ? [nextToken, ...continuationTokens.slice(0, generationIndex - 1)] : [])
  ];
  elements.generatedText.textContent = visibleTokens.join(" ");
  elements.generationContext.innerHTML = visibleTokens
    .map(token => `<span class="token-pill">${escapeHtml(token)}</span>`)
    .join("");
  elements.stepGenerateButton.disabled = generationIndex >= selectedContext.generationTokens.length;
}

function resetGeneration() {
  stopGenerationAuto();
  generationIndex = 0;
  renderGeneration();
}

function toggleGenerationAuto() {
  if (generationTimer) {
    stopGenerationAuto();
    return;
  }

  elements.autoGenerateButton.textContent = "Pause Generation";
  generationTimer = window.setInterval(() => {
    if (generationIndex >= selectedContext.generationTokens.length) {
      stopGenerationAuto();
      return;
    }
    stepGeneration();
  }, 720);
}

function stopGenerationAuto() {
  if (generationTimer) {
    window.clearInterval(generationTimer);
    generationTimer = null;
  }
  elements.autoGenerateButton.textContent = "Auto Generate";
}

function revealHallucination() {
  elements.hallucinationDemo.hidden = false;
}

function renderHallucinationProbabilities() {
  elements.hallucinationProbabilities.innerHTML = hallucinationTokens
    .map(([token, value]) => probabilityRow(token, value))
    .join("");
}

function probabilityRow(token, value) {
  return `
    <div class="probability-row" data-token="${escapeHtml(token)}">
      <strong>${escapeHtml(token)}</strong>
      <span class="probability-track"><i class="probability-fill" style="--value:${value}"></i></span>
      <span>${value}%</span>
    </div>
  `;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
